package typings
package activexDashInfopathLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait EnumeratorConstructor
  extends  // tslint:disable-line:use-default-type-parameter
org.scalablytyped.runtime.Instantiable1[
      (/* col */ activexDashInfopathLib.InfoPathNs.DataAdaptersCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.DataObjectsCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.ErrorsCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.InputParameterCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.PermissionObject) | (/* col */ activexDashInfopathLib.InfoPathNs.SignatureLinesCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.SignaturesCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.SignedDataBlocksCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.TaskPanesCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.ViewInfosCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.WindowsCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.XDocuments) | (/* col */ activexDashInfopathLib.InfoPathNs.XDocumentsCollection) | (/* col */ activexDashInfopathLib.InfoPathNs.XMLNodesCollection), 
      (activexDashInteropLib.Enumerator[_] with stdLib.Enumerator[_]) | (activexDashInteropLib.Enumerator[activexDashInfopathLib.InfoPathNs.DataSourceObject] with stdLib.Enumerator[activexDashInfopathLib.InfoPathNs.DataSourceObject]) | (activexDashInteropLib.Enumerator[activexDashAdodbLib.ADODBNs.Error] with stdLib.Enumerator[activexDashAdodbLib.ADODBNs.Error]) | (activexDashInteropLib.Enumerator[activexDashInfopathLib.InfoPathNs.InputParameterObject] with stdLib.Enumerator[activexDashInfopathLib.InfoPathNs.InputParameterObject]) | (activexDashInteropLib.Enumerator[activexDashInfopathLib.InfoPathNs.UserPermissionObject] with stdLib.Enumerator[activexDashInfopathLib.InfoPathNs.UserPermissionObject]) | (activexDashInteropLib.Enumerator[activexDashInfopathLib.InfoPathNs.SignatureLineObject] with stdLib.Enumerator[activexDashInfopathLib.InfoPathNs.SignatureLineObject]) | (activexDashInteropLib.Enumerator[activexDashInfopathLib.InfoPathNs.SignatureObject] with stdLib.Enumerator[activexDashInfopathLib.InfoPathNs.SignatureObject]) | (activexDashInteropLib.Enumerator[activexDashInfopathLib.InfoPathNs.SignedDataBlockObject] with stdLib.Enumerator[activexDashInfopathLib.InfoPathNs.SignedDataBlockObject]) | (activexDashInteropLib.Enumerator[activexDashInfopathLib.InfoPathNs.TaskPaneObject] with stdLib.Enumerator[activexDashInfopathLib.InfoPathNs.TaskPaneObject]) | (activexDashInteropLib.Enumerator[activexDashInfopathLib.InfoPathNs.ViewInfoObject] with stdLib.Enumerator[activexDashInfopathLib.InfoPathNs.ViewInfoObject]) | (activexDashInteropLib.Enumerator[activexDashInfopathLib.InfoPathNs.Window] with stdLib.Enumerator[activexDashInfopathLib.InfoPathNs.Window]) | (activexDashInteropLib.Enumerator[activexDashInfopathLib.InfoPathNs._XDocument] with stdLib.Enumerator[activexDashInfopathLib.InfoPathNs._XDocument]) | (activexDashInteropLib.Enumerator[activexDashMsxml2Lib.MSXML2Ns.IXMLDOMNode] with stdLib.Enumerator[activexDashMsxml2Lib.MSXML2Ns.IXMLDOMNode])
    ]

