package typings
package rxDashJqueryLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait JQueryStatic extends js.Object {
  def ajaxAsObservable[T](settings: jqueryLib.JQueryAjaxSettings): rxDashLiteDashAggregatesLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashCoreLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashExperimentalLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashBackpressureLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashTimeLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashCoincidenceLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashCoreDashBindingLib.RxNs.Observable[RxJQueryAjaxResult[T]]
  def getAsObservable[T](url: java.lang.String, data: js.Any, dataType: java.lang.String): rxDashLiteDashAggregatesLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashCoreLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashExperimentalLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashBackpressureLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashTimeLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashCoincidenceLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashCoreDashBindingLib.RxNs.Observable[RxJQueryAjaxResult[T]]
  def getJSONAsObservable[T](url: java.lang.String, data: js.Any): rxDashLiteDashAggregatesLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashCoreLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashExperimentalLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashBackpressureLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashTimeLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashCoincidenceLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashCoreDashBindingLib.RxNs.Observable[RxJQueryAjaxResult[T]]
  def getScriptAsObservable[T](url: java.lang.String, data: js.Any): rxDashLiteDashAggregatesLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashCoreLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashExperimentalLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashBackpressureLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashTimeLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashCoincidenceLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashCoreDashBindingLib.RxNs.Observable[RxJQueryAjaxResult[T]]
  def postAsObservable[T](url: java.lang.String, data: js.Any, dataType: java.lang.String): rxDashLiteDashAggregatesLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashCoreLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashExperimentalLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashBackpressureLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashTimeLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashLiteDashCoincidenceLib.RxNs.Observable[RxJQueryAjaxResult[T]] with rxDashCoreDashBindingLib.RxNs.Observable[RxJQueryAjaxResult[T]]
}

