package typings
package rxDashDomLib.rxDashDomMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("rx-dom", "DOM")
@js.native
object DOMNs extends js.Object {
  def ajax(settingsOrUrl: java.lang.String): rxDashLiteDashAggregatesLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashCoreLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashExperimentalLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashBackpressureLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashTimeLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashCoincidenceLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashCoreDashBindingLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] = js.native
  // Ajax
  def ajax(settingsOrUrl: rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSettings): rxDashLiteDashAggregatesLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashCoreLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashExperimentalLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashBackpressureLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashTimeLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashCoincidenceLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashCoreDashBindingLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] = js.native
  // Event Shortcuts
  def blur(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.FocusEvent] = js.native
  def blur(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.FocusEvent] = js.native
  def blur(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.FocusEvent] = js.native
  def change(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def change(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def click(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def click(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def click(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def contextmenu(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def contextmenu(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def contextmenu(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def dblclick(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def dblclick(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def dblclick(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def error(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def error(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def error(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def focus(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.FocusEvent] = js.native
  def focus(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.FocusEvent] = js.native
  def focus(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.FocusEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.FocusEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.FocusEvent] = js.native
  def focusin(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def focusin(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def focusin(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def focusout(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def focusout(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def focusout(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  // Events
  def fromEvent[T](element: js.Any, eventName: java.lang.String): rxDashLiteDashAggregatesLib.RxNs.Observable[T] with rxDashCoreLib.RxNs.Observable[T] with rxDashLiteLib.RxNs.Observable[T] with rxDashLiteDashExperimentalLib.RxNs.Observable[T] with rxDashLiteDashBackpressureLib.RxNs.Observable[T] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[T] with rxDashLiteDashTimeLib.RxNs.Observable[T] with rxDashLiteDashCoincidenceLib.RxNs.Observable[T] with rxDashCoreDashBindingLib.RxNs.Observable[T] = js.native
  def fromEvent[T](element: js.Any, eventName: java.lang.String, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[T] with rxDashCoreLib.RxNs.Observable[T] with rxDashLiteLib.RxNs.Observable[T] with rxDashLiteDashExperimentalLib.RxNs.Observable[T] with rxDashLiteDashBackpressureLib.RxNs.Observable[T] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[T] with rxDashLiteDashTimeLib.RxNs.Observable[T] with rxDashLiteDashCoincidenceLib.RxNs.Observable[T] with rxDashCoreDashBindingLib.RxNs.Observable[T] = js.native
  def fromEvent[T](element: js.Any, eventName: java.lang.String, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[T] with rxDashCoreLib.RxNs.Observable[T] with rxDashLiteLib.RxNs.Observable[T] with rxDashLiteDashExperimentalLib.RxNs.Observable[T] with rxDashLiteDashBackpressureLib.RxNs.Observable[T] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[T] with rxDashLiteDashTimeLib.RxNs.Observable[T] with rxDashLiteDashCoincidenceLib.RxNs.Observable[T] with rxDashCoreDashBindingLib.RxNs.Observable[T] = js.native
  // Server-Sent Events
  def fromEventSource[T](url: java.lang.String): rxDashLiteDashAggregatesLib.RxNs.Observable[T] with rxDashCoreLib.RxNs.Observable[T] with rxDashLiteLib.RxNs.Observable[T] with rxDashLiteDashExperimentalLib.RxNs.Observable[T] with rxDashLiteDashBackpressureLib.RxNs.Observable[T] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[T] with rxDashLiteDashTimeLib.RxNs.Observable[T] with rxDashLiteDashCoincidenceLib.RxNs.Observable[T] with rxDashCoreDashBindingLib.RxNs.Observable[T] = js.native
  def fromEventSource[T](
    url: java.lang.String,
    openObservable: rxDashCoreLib.RxNs.Observer[T] with rxDashLiteLib.RxNs.Observer[T]
  ): rxDashLiteDashAggregatesLib.RxNs.Observable[T] with rxDashCoreLib.RxNs.Observable[T] with rxDashLiteLib.RxNs.Observable[T] with rxDashLiteDashExperimentalLib.RxNs.Observable[T] with rxDashLiteDashBackpressureLib.RxNs.Observable[T] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[T] with rxDashLiteDashTimeLib.RxNs.Observable[T] with rxDashLiteDashCoincidenceLib.RxNs.Observable[T] with rxDashCoreDashBindingLib.RxNs.Observable[T] = js.native
  // Mutation Observers
  def fromMutationObserver(target: stdLib.Node, options: stdLib.MutationObserverInit): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MutationEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MutationEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MutationEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MutationEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MutationEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MutationEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MutationEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MutationEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MutationEvent] = js.native
  // Web Sockets
  def fromWebSocket(url: java.lang.String, protocol: java.lang.String): rxDashCoreDashBindingLib.RxNs.Subject[stdLib.MessageEvent] = js.native
  def fromWebSocket(
    url: java.lang.String,
    protocol: java.lang.String,
    openObserver: rxDashCoreLib.RxNs.Observer[stdLib.Event] with rxDashLiteLib.RxNs.Observer[stdLib.Event]
  ): rxDashCoreDashBindingLib.RxNs.Subject[stdLib.MessageEvent] = js.native
  def fromWebSocket(
    url: java.lang.String,
    protocol: java.lang.String,
    openObserver: rxDashCoreLib.RxNs.Observer[stdLib.Event] with rxDashLiteLib.RxNs.Observer[stdLib.Event],
    closingObserver: rxDashCoreLib.RxNs.Observer[stdLib.CloseEvent] with rxDashLiteLib.RxNs.Observer[stdLib.CloseEvent]
  ): rxDashCoreDashBindingLib.RxNs.Subject[stdLib.MessageEvent] = js.native
  // Web Workers
  def fromWebWorker(url: java.lang.String): rxDashCoreDashBindingLib.RxNs.Subject[java.lang.String] = js.native
  def get(url: java.lang.String): rxDashLiteDashAggregatesLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashCoreLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashExperimentalLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashBackpressureLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashTimeLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashCoincidenceLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashCoreDashBindingLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] = js.native
  def getJSON(url: java.lang.String): rxDashLiteDashAggregatesLib.RxNs.Observable[java.lang.String] with rxDashCoreLib.RxNs.Observable[java.lang.String] with rxDashLiteLib.RxNs.Observable[java.lang.String] with rxDashLiteDashExperimentalLib.RxNs.Observable[java.lang.String] with rxDashLiteDashBackpressureLib.RxNs.Observable[java.lang.String] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[java.lang.String] with rxDashLiteDashTimeLib.RxNs.Observable[java.lang.String] with rxDashLiteDashCoincidenceLib.RxNs.Observable[java.lang.String] with rxDashCoreDashBindingLib.RxNs.Observable[java.lang.String] = js.native
  def jsonpRequest(settings: rxDashDomLib.rxDashDomMod.rxMod.DOMNs.JsonpSettings): rxDashLiteDashAggregatesLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.JsonpSuccessResponse] with rxDashCoreLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.JsonpSuccessResponse] with rxDashLiteLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.JsonpSuccessResponse] with rxDashLiteDashExperimentalLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.JsonpSuccessResponse] with rxDashLiteDashBackpressureLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.JsonpSuccessResponse] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.JsonpSuccessResponse] with rxDashLiteDashTimeLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.JsonpSuccessResponse] with rxDashLiteDashCoincidenceLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.JsonpSuccessResponse] with rxDashCoreDashBindingLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.JsonpSuccessResponse] = js.native
  def jsonpRequest(url: java.lang.String): rxDashLiteDashAggregatesLib.RxNs.Observable[java.lang.String] with rxDashCoreLib.RxNs.Observable[java.lang.String] with rxDashLiteLib.RxNs.Observable[java.lang.String] with rxDashLiteDashExperimentalLib.RxNs.Observable[java.lang.String] with rxDashLiteDashBackpressureLib.RxNs.Observable[java.lang.String] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[java.lang.String] with rxDashLiteDashTimeLib.RxNs.Observable[java.lang.String] with rxDashLiteDashCoincidenceLib.RxNs.Observable[java.lang.String] with rxDashCoreDashBindingLib.RxNs.Observable[java.lang.String] = js.native
  def keydown(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.KeyboardEvent] = js.native
  def keydown(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.KeyboardEvent] = js.native
  def keydown(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.KeyboardEvent] = js.native
  def keypress(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.KeyboardEvent] = js.native
  def keypress(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.KeyboardEvent] = js.native
  def keypress(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.KeyboardEvent] = js.native
  def keyup(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.KeyboardEvent] = js.native
  def keyup(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.KeyboardEvent] = js.native
  def keyup(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.KeyboardEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.KeyboardEvent] = js.native
  def load(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.UIEvent] = js.native
  def load(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.UIEvent] = js.native
  def load(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.UIEvent] = js.native
  def mousedown(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mousedown(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mousedown(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseenter(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseenter(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseenter(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseleave(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseleave(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseleave(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mousemove(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mousemove(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mousemove(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseout(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseout(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseout(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseover(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseover(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseover(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseup(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseup(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  def mouseup(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.MouseEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.MouseEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.MouseEvent] = js.native
  // Pointer Events
  def pointerdown(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerdown(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerdown(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerenter(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerenter(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerenter(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerleave(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerleave(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerleave(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointermove(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointermove(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointermove(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerout(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerout(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerout(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerover(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerover(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerover(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerup(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerup(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def pointerup(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.PointerEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.PointerEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.PointerEvent] = js.native
  def post(url: java.lang.String, body: js.Any): rxDashLiteDashAggregatesLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashCoreLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashExperimentalLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashBackpressureLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashTimeLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashLiteDashCoincidenceLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] with rxDashCoreDashBindingLib.RxNs.Observable[rxDashDomLib.rxDashDomMod.rxMod.DOMNs.AjaxSuccessResponse] = js.native
  def ready(): rxDashLiteDashAggregatesLib.RxNs.Observable[_] with rxDashCoreLib.RxNs.Observable[_] with rxDashLiteLib.RxNs.Observable[_] with rxDashLiteDashExperimentalLib.RxNs.Observable[_] with rxDashLiteDashBackpressureLib.RxNs.Observable[_] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[_] with rxDashLiteDashTimeLib.RxNs.Observable[_] with rxDashLiteDashCoincidenceLib.RxNs.Observable[_] with rxDashCoreDashBindingLib.RxNs.Observable[_] = js.native
  def resize(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.UIEvent] = js.native
  def resize(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.UIEvent] = js.native
  def resize(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.UIEvent] = js.native
  def scroll(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.UIEvent] = js.native
  def scroll(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.UIEvent] = js.native
  def scroll(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.UIEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.UIEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.UIEvent] = js.native
  def select(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def select(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def select(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def submit(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def submit(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def submit(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  // Touch Events
  def touchcancel(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchcancel(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchcancel(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchend(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchend(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchend(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchmove(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchmove(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchmove(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchstart(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchstart(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def touchstart(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.TouchEvent] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.TouchEvent] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.TouchEvent] = js.native
  def unload(element: stdLib.Element): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def unload(element: stdLib.Element, selector: js.Function): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  def unload(element: stdLib.Element, selector: js.Function, useCapture: scala.Boolean): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Event] with rxDashCoreLib.RxNs.Observable[stdLib.Event] with rxDashLiteLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Event] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Event] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Event] = js.native
  // Geolocation
  @JSName("geolocation")
  @js.native
  object geolocationNs extends js.Object {
    def getCurrentPosition(): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Position] with rxDashCoreLib.RxNs.Observable[stdLib.Position] with rxDashLiteLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Position] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Position] = js.native
    def getCurrentPosition(geolocationOptions: rxDashDomLib.rxDashDomMod.rxMod.DOMNs.GeolocationOptions): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Position] with rxDashCoreLib.RxNs.Observable[stdLib.Position] with rxDashLiteLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Position] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Position] = js.native
    def watchPosition(): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Position] with rxDashCoreLib.RxNs.Observable[stdLib.Position] with rxDashLiteLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Position] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Position] = js.native
    def watchPosition(geolocationOptions: rxDashDomLib.rxDashDomMod.rxMod.DOMNs.GeolocationOptions): rxDashLiteDashAggregatesLib.RxNs.Observable[stdLib.Position] with rxDashCoreLib.RxNs.Observable[stdLib.Position] with rxDashLiteLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashExperimentalLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashBackpressureLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashJoinpatternsLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashTimeLib.RxNs.Observable[stdLib.Position] with rxDashLiteDashCoincidenceLib.RxNs.Observable[stdLib.Position] with rxDashCoreDashBindingLib.RxNs.Observable[stdLib.Position] = js.native
  }
  
}

