package typings
package sparkpostLib.sparkpostMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait SparkPost extends js.Object {
  /** Specifying an inbound domain enables you to customize the address to which inbound messages are sent. */
  var inboundDomains: sparkpostLib.Anon_List = js.native
  /** The Message Events API provides the means to search the raw events generated by SparkPost. */
  var messageEvents: sparkpostLib.Anon_Search = js.native
  /** A recipient list is a collection of recipients that can be used in a transmission. */
  var recipientLists: sparkpostLib.Anon_ListCallback = js.native
  /** Relay Webhooks are a way to instruct SparkPost to accept inbound email on your behalf and forward it to you over HTTP for your own consumption. */
  var relayWebhooks: sparkpostLib.Anon_ListCallbackGet = js.native
  var sendingDomains: sparkpostLib.Anon_ListCallbackGetDomain = js.native
  var subaccounts: sparkpostLib.Anon_ListCallbackGetId = js.native
  var suppressionList: sparkpostLib.Anon_ListCallbackParameters = js.native
  var templates: sparkpostLib.Anon_ListCallbackGetIdOptions = js.native
  var transmissions: sparkpostLib.Anon_ListCallbackOptions = js.native
  var webhooks: sparkpostLib.Anon_ListCallbackOptionsGet = js.native
  def delete(options: requestLib.requestMod.requestNs.Options): js.Promise[sparkpostLib.sparkpostMod.SparkPostNs.Response[_]] = js.native
  def delete(
    options: requestLib.requestMod.requestNs.Options,
    callback: sparkpostLib.sparkpostMod.SparkPostNs.Callback[_]
  ): scala.Unit = js.native
  def get(options: requestLib.requestMod.requestNs.Options): js.Promise[sparkpostLib.sparkpostMod.SparkPostNs.Response[_]] = js.native
  def get(
    options: requestLib.requestMod.requestNs.Options,
    callback: sparkpostLib.sparkpostMod.SparkPostNs.Callback[_]
  ): scala.Unit = js.native
  def post(options: requestLib.requestMod.requestNs.Options): js.Promise[sparkpostLib.sparkpostMod.SparkPostNs.Response[_]] = js.native
  def post(
    options: requestLib.requestMod.requestNs.Options,
    callback: sparkpostLib.sparkpostMod.SparkPostNs.Callback[_]
  ): scala.Unit = js.native
  def put(options: requestLib.requestMod.requestNs.Options): js.Promise[sparkpostLib.sparkpostMod.SparkPostNs.Response[_]] = js.native
  def put(
    options: requestLib.requestMod.requestNs.Options,
    callback: sparkpostLib.sparkpostMod.SparkPostNs.Callback[_]
  ): scala.Unit = js.native
  def request(options: requestLib.requestMod.requestNs.Options): js.Promise[sparkpostLib.sparkpostMod.SparkPostNs.Response[_]] = js.native
  def request(
    options: requestLib.requestMod.requestNs.Options,
    callback: sparkpostLib.sparkpostMod.SparkPostNs.Callback[_]
  ): scala.Unit = js.native
}

