package typings
package vsoDashNodeDashApiLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Anon_AgentArtifactDefinition extends js.Object {
  var AgentArtifactDefinition: js.Any
  var AgentArtifactType: Anon_EnumValuesAnonXamlBuild
  var AgentBasedDeployPhase: js.Any
  var AgentDeploymentInput: js.Any
  var ApprovalExecutionOrder: Anon_EnumValuesAnonBeforeGates
  var ApprovalFilters: Anon_EnumValuesAnonNoneManualApprovals
  var ApprovalOptions: js.Any
  var ApprovalStatus: Anon_EnumValuesAnonUndefinedPending
  var ApprovalType: Anon_EnumValuesAnonUndefinedPreDeploy
  var ArtifactContributionDefinition: js.Any
  var ArtifactSourceTrigger: js.Any
  var ArtifactTypeDefinition: js.Any
  var AuditAction: Anon_EnumValuesAnonAddUpdate
  var AuthorizationHeaderFor: Anon_EnumValuesAnonRevalidateApproverIdentity
  var AutoTriggerIssue: js.Any
  var AzureKeyVaultVariableGroupProviderData: js.Any
  var AzureKeyVaultVariableValue: js.Any
  var Change: js.Any
  var Condition: js.Any
  var ConditionType: Anon_EnumValuesAnonUndefinedEvent
  var ContainerImageTrigger: js.Any
  var ContinuousDeploymentTriggerIssue: js.Any
  var DeployPhase: js.Any
  var DeployPhaseStatus: Anon_EnumValuesAnonUndefinedNotStarted
  var DeployPhaseTypes: Anon_EnumValuesAnonUndefinedAgentBasedDeployment
  var Deployment: js.Any
  var DeploymentApprovalCompletedEvent: js.Any
  var DeploymentApprovalPendingEvent: js.Any
  var DeploymentAttempt: js.Any
  var DeploymentAuthorizationInfo: js.Any
  var DeploymentAuthorizationOwner: Anon_EnumValuesAnonAutomatic
  var DeploymentCompletedEvent: js.Any
  var DeploymentExpands: Anon_EnumValuesAnonAll
  var DeploymentJob: js.Any
  var DeploymentManualInterventionPendingEvent: js.Any
  var DeploymentOperationStatus: Anon_EnumValuesAnonUndefinedQueued
  var DeploymentQueryParameters: js.Any
  var DeploymentReason: Anon_EnumValuesAnonNoneManual
  var DeploymentStartedEvent: js.Any
  var DeploymentStatus: Anon_EnumValuesAnonUndefinedNotDeployed
  var DeploymentsQueryType: Anon_EnumValuesAnonRegular
  var EnvironmentStatus: Anon_EnumValuesAnonUndefinedNotStartedInProgress
  var ExecutionInput: js.Any
  var Folder: js.Any
  var FolderPathQueryOrder: Anon_EnumValuesAnonNoneAscending
  var GateStatus: Anon_EnumValuesAnonNonePending
  var IssueSource: Anon_EnumValuesAnonNoneUser
  var MachineGroupBasedDeployPhase: js.Any
  var MailMessage: js.Any
  var MailSectionType: Anon_EnumValuesAnonDetails
  var ManualIntervention: js.Any
  var ManualInterventionStatus: Anon_EnumValuesAnonUnknownPending
  var ManualInterventionUpdateMetadata: js.Any
  var MultiConfigInput: js.Any
  var MultiMachineInput: js.Any
  var PackageTrigger: js.Any
  var ParallelExecutionInputBase: js.Any
  var ParallelExecutionTypes: Anon_EnumValuesAnonNoneMultiConfiguration
  var PipelineProcess: js.Any
  var PipelineProcessTypes: Anon_EnumValuesAnonDesigner
  var PropertySelector: js.Any
  var PropertySelectorType: Anon_EnumValuesAnonInclusion
  var Release: js.Any
  var ReleaseAbandonedEvent: js.Any
  var ReleaseApproval: js.Any
  var ReleaseApprovalHistory: js.Any
  var ReleaseApprovalPendingEvent: js.Any
  var ReleaseCondition: js.Any
  var ReleaseCreatedEvent: js.Any
  var ReleaseDefinition: js.Any
  var ReleaseDefinitionApprovals: js.Any
  var ReleaseDefinitionEnvironment: js.Any
  var ReleaseDefinitionEnvironmentTemplate: js.Any
  var ReleaseDefinitionExpands: Anon_EnumValuesAnonNoneEnvironments
  var ReleaseDefinitionQueryOrder: Anon_EnumValuesAnonIdAscending
  var ReleaseDefinitionRevision: js.Any
  var ReleaseDefinitionSource: Anon_EnumValuesAnonUndefinedRestApi
  var ReleaseDefinitionSummary: js.Any
  var ReleaseDeployPhase: js.Any
  var ReleaseEnvironment: js.Any
  var ReleaseEnvironmentCompletedEvent: js.Any
  var ReleaseEnvironmentUpdateMetadata: js.Any
  var ReleaseExpands: Anon_EnumValuesAnonNoneEnvironmentsArtifacts
  var ReleaseGates: js.Any
  var ReleaseQueryOrder: Anon_EnumValuesAnonDescending
  var ReleaseReason: Anon_EnumValuesAnonNoneManualContinuousIntegration
  var ReleaseReference: js.Any
  var ReleaseRevision: js.Any
  var ReleaseSchedule: js.Any
  var ReleaseStartMetadata: js.Any
  var ReleaseStatus: Anon_EnumValuesAnonUndefinedDraft
  var ReleaseTask: js.Any
  var ReleaseTaskAttachment: js.Any
  var ReleaseTasksUpdatedEvent: js.Any
  var ReleaseTriggerBase: js.Any
  var ReleaseTriggerType: Anon_EnumValuesAnonUndefinedArtifactSource
  var ReleaseUpdateMetadata: js.Any
  var ReleaseUpdatedEvent: js.Any
  var RunOnServerDeployPhase: js.Any
  var ScheduleDays: Anon_EnumValuesAnonNoneMonday
  var ScheduledReleaseTrigger: js.Any
  var SenderType: Anon_EnumValuesAnonServiceAccount
  var ServerDeploymentInput: js.Any
  var SourceRepoTrigger: js.Any
  var SummaryMailSection: js.Any
  var TaskStatus: Anon_EnumValuesAnonUnknownPendingInProgress
  var VariableGroup: js.Any
  var VariableGroupActionFilter: Anon_EnumValuesAnonNoneManage
}

