package typings
package vsoDashNodeDashApiLib

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Anon_Attachment extends js.Object {
  var Attachment: js.Any
  var Change: js.Any
  var ChangeList: js.Any
  var Comment: js.Any
  var CommentThread: js.Any
  var CommentThreadStatus: Anon_EnumValuesAnonUnknownActive
  var CommentType: Anon_EnumValuesAnonUnknownText
  var GitAnnotatedTag: js.Any
  var GitAsyncOperationStatus: Anon_EnumValuesAnonQueued
  var GitAsyncRefOperation: js.Any
  var GitAsyncRefOperationDetail: js.Any
  var GitAsyncRefOperationFailureStatus: Anon_EnumValuesAnonNoneInvalidRefName
  var GitAsyncRefOperationParameters: js.Any
  var GitAsyncRefOperationSource: js.Any
  var GitBaseVersionDescriptor: js.Any
  var GitBranchStats: js.Any
  var GitChange: js.Any
  var GitCherryPick: js.Any
  var GitCommit: js.Any
  var GitCommitChanges: js.Any
  var GitCommitDiffs: js.Any
  var GitCommitRef: js.Any
  var GitCommitToCreate: js.Any
  var GitConflict: js.Any
  var GitConflictAddAdd: js.Any
  var GitConflictAddRename: js.Any
  var GitConflictDeleteEdit: js.Any
  var GitConflictDeleteRename: js.Any
  var GitConflictDirectoryFile: js.Any
  var GitConflictEditDelete: js.Any
  var GitConflictEditEdit: js.Any
  var GitConflictFileDirectory: js.Any
  var GitConflictRename1to2: js.Any
  var GitConflictRename2to1: js.Any
  var GitConflictRenameAdd: js.Any
  var GitConflictRenameDelete: js.Any
  var GitConflictRenameRename: js.Any
  var GitConflictType: Anon_EnumValuesAnonNoneAddAdd
  var GitConflictUpdateResult: js.Any
  var GitConflictUpdateStatus: Anon_EnumValuesAnonSucceededBadRequest
  var GitDeletedRepository: js.Any
  var GitForkRef: js.Any
  var GitForkSyncRequest: js.Any
  var GitHistoryMode: Anon_EnumValuesAnonSimplifiedHistory
  var GitImportFailedEvent: js.Any
  var GitImportRequest: js.Any
  var GitImportSucceededEvent: js.Any
  var GitItem: js.Any
  var GitItemDescriptor: js.Any
  var GitItemRequestData: js.Any
  var GitLastChangeTreeItems: js.Any
  var GitObject: js.Any
  var GitObjectType: Anon_EnumValuesAnonBad
  var GitPathAction: js.Any
  var GitPathActions: Anon_EnumValuesAnonNoneEditDelete
  var GitPathToItemsCollection: js.Any
  var GitPullRequest: js.Any
  var GitPullRequestChange: js.Any
  var GitPullRequestCommentThread: js.Any
  var GitPullRequestIteration: js.Any
  var GitPullRequestIterationChanges: js.Any
  var GitPullRequestQuery: js.Any
  var GitPullRequestQueryInput: js.Any
  var GitPullRequestQueryType: Anon_EnumValuesAnonNotSet
  var GitPullRequestReviewFileType: Anon_EnumValuesAnonChangeEntry
  var GitPullRequestSearchCriteria: js.Any
  var GitPullRequestStatus: js.Any
  var GitPush: js.Any
  var GitPushEventData: js.Any
  var GitPushRef: js.Any
  var GitPushSearchCriteria: js.Any
  var GitQueryBranchStatsCriteria: js.Any
  var GitQueryCommitsCriteria: js.Any
  var GitQueryRefsCriteria: js.Any
  var GitRef: js.Any
  var GitRefFavorite: js.Any
  var GitRefSearchType: Anon_EnumValuesAnonExact
  var GitRefUpdateMode: Anon_EnumValuesAnonBestEffort
  var GitRefUpdateResult: js.Any
  var GitRefUpdateStatus: Anon_EnumValuesAnonSucceededForcePushRequired
  var GitRepository: js.Any
  var GitRepositoryCreateOptions: js.Any
  var GitRepositoryRef: js.Any
  var GitResolutionError: Anon_EnumValuesAnonNoneMergeContentNotFound
  var GitResolutionMergeContent: js.Any
  var GitResolutionMergeType: Anon_EnumValuesAnonUndecided
  var GitResolutionPathConflict: js.Any
  var GitResolutionPathConflictAction: Anon_EnumValuesAnonUndecidedKeepSourceRenameTarget
  var GitResolutionPickOneAction: js.Any
  var GitResolutionRename1to2: js.Any
  var GitResolutionRename1to2Action: Anon_EnumValuesAnonUndecidedKeepSourcePath
  var GitResolutionStatus: Anon_EnumValuesAnonUnresolved
  var GitResolutionWhichAction: Anon_EnumValuesAnonUndecidedPickSourceAction
  var GitRevert: js.Any
  var GitStatus: js.Any
  var GitStatusState: Anon_EnumValuesAnonNotSetPending
  var GitTargetVersionDescriptor: js.Any
  var GitTreeDiff: js.Any
  var GitTreeDiffEntry: js.Any
  var GitTreeDiffResponse: js.Any
  var GitTreeEntryRef: js.Any
  var GitTreeRef: js.Any
  var GitUserDate: js.Any
  var GitVersionDescriptor: js.Any
  var GitVersionOptions: Anon_EnumValuesAnonNonePreviousChange
  var GitVersionType: Anon_EnumValuesAnonBranch
  var HistoryEntry: js.Any
  var IncludedGitCommit: js.Any
  var ItemContent: js.Any
  var ItemContentType: Anon_EnumValuesAnonRawText
  var ItemDetailsOptions: js.Any
  var IterationReason: Anon_EnumValuesAnonPush
  var PullRequestAsyncStatus: Anon_EnumValuesAnonNotSetQueued
  var PullRequestMergeFailureType: Anon_EnumValuesAnonNoneUnknown
  var PullRequestStatus: Anon_EnumValuesAnonNotSetActive
  var RefFavoriteType: Anon_EnumValuesAnonInvalid
  var SupportedIde: js.Any
  var SupportedIdeType: Anon_EnumValuesAnonUnknownAndroidStudio
  var TfvcBranch: js.Any
  var TfvcBranchRef: js.Any
  var TfvcChange: js.Any
  var TfvcChangeset: js.Any
  var TfvcChangesetRef: js.Any
  var TfvcCheckinEventData: js.Any
  var TfvcHistoryEntry: js.Any
  var TfvcItem: js.Any
  var TfvcItemDescriptor: js.Any
  var TfvcItemRequestData: js.Any
  var TfvcLabel: js.Any
  var TfvcLabelRef: js.Any
  var TfvcShelveset: js.Any
  var TfvcShelvesetRef: js.Any
  var TfvcVersionDescriptor: js.Any
  var TfvcVersionOption: Anon_EnumValuesAnonNonePrevious
  var TfvcVersionType: Anon_EnumValuesAnonNoneChangeset
  var UpdateRefsRequest: js.Any
  var VersionControlChangeType: Anon_EnumValuesAnonNoneAdd
  var VersionControlProjectInfo: js.Any
  var VersionControlRecursionType: Anon_EnumValuesAnonNoneOneLevel
}

